language: cpp

sudo: required
dist: xenial

addons:
  apt:
    packages:
      - valgrind

env:
  global:
    - CTEST_EXT_COLOR_OUTPUT=TRUE
    - CTEST_BUILD_FLAGS=-j4

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - CTEST_TARGET_SYSTEM=Linux-gcc    CTEST_MODEL=Nightly
        - MATRIX_EVAL="CC=gcc-8 &&CXX=g++-8"
    - os: linux
      compiler: clang
      addons:
        apt:
            sources:
              - llvm-toolchain-trusty-6.0
            packages:
              - clang-6.0
      env:
        - CTEST_TARGET_SYSTEM=Linux-clang  CTEST_MODEL=Nightly
        - MATRIX_EVAL="CC=clang-6.0 &&CXX=clang++-6.0"
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - echo $CC
  - mkdir build && cd build && cmake .. && make -j && ctest
