language: cpp

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - valgrind

env:
  global:
    - CTEST_EXT_COLOR_OUTPUT=TRUE
    - CTEST_BUILD_FLAGS=-j4

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CTEST_TARGET_SYSTEM=Linux-gcc    CTEST_MODEL=Nightly
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      compiler: clang
      env: CTEST_TARGET_SYSTEM=MacOS-clang  CTEST_MODEL=Nightly

script:
  - mkdir build && cd build && cmake .. && make -j && ctest
